version: 'latest'
services:
  nginx: 
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro


  node-app:
    build: .

    environment:
      - PORT=3000
    depends_on:
      - mongo
    # env_file:
    #   - ./.env


  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sanjeev
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo-db:/data/db
  
  redis: 
    image: redis

volumes:
  mongo-db: